create database QLTC
go
use QLTC

CREATE TABLE KHACHHANG
(
	MAKH CHAR(8) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	DIACHI NVARCHAR(200),
	NGAYSINH DATE, 
	SDT CHAR(10)
);

CREATE TABLE VACCINE 
(
	MAVC CHAR(8) PRIMARY KEY, 
	TENVACCINE VARCHAR(50), 
	XUATXU VARCHAR(30), 
	SLT INT, 
	GIA DECIMAL(19,4)
);

CREATE TABLE HOSOTIEMCHUNG 
(	
	MAHS CHAR(8) PRIMARY KEY,
	NGAYLAP DATE, 
	MAKH CHAR(8)
);

CREATE TABLE CT_HSTC 
(
	MAHS CHAR(8) NOT NULL, 
	MAVC CHAR(8) NOT NULL, 
	NGAYTIEM DATE
);

ALTER TABLE CT_HSTC 
ADD CONSTRAINT PK_CT_HSTC PRIMARY KEY (MAHS, MAVC);

CREATE TABLE DSDATVACCINE 
(
	MADS CHAR(8) PRIMARY KEY, 
	NGAYLAP DATE, 
	MANV CHAR(8)
);

CREATE TABLE CT_DSDAT 
(
	MADS CHAR(8) NOT NULL, 
	MAVC CHAR(8) NOT NULL, 
	SOLUONG INT
);

ALTER TABLE CT_DSDAT 
ADD CONSTRAINT PK_CT_DSDAT PRIMARY KEY (MADS, MAVC);

CREATE TABLE PHIEUDKTIEM 
(
	MAPDKTIEM CHAR(8) PRIMARY KEY, 
	MAKH CHAR(8), 
	DIACHI NVARCHAR(200), 
	GIOITINH BIT, 
	NGAYTIEM DATE, 
	HOTEN NVARCHAR(50), 
	SDT CHAR(10), 
	HOTEN_NGH NVARCHAR(50), 
	SDT_NGH CHAR(10), 
	MQH NVARCHAR(20)
);

CREATE TABLE HOADON 
(
	MAHD CHAR(10) PRIMARY KEY, 
	HINHTHUC VARCHAR(10), 
	SOTIEN DECIMAL(19, 4),
	MAPDKTIEM CHAR(8)
);

CREATE TABLE NHANVIEN 
(
	MANV CHAR(8) PRIMARY KEY, 
	HOTEN NVARCHAR(50), 
	NGAYSINH DATE, 
	BANGCAP NVARCHAR(30), 
	SDT CHAR(10), 
	TTLAMVIEC NVARCHAR(10), 
	VITRI VARCHAR(10)
);

CREATE TABLE DONMUAVC 
(
	MADON CHAR(8) PRIMARY KEY, 
	MAKH CHAR(8), 
	NGAYDATMUA DATE, 
	TONGTIEN DECIMAL(19,4)
);

CREATE TABLE CT_DMVC
(
	MADON CHAR(8) NOT NULL, 
	MAVC CHAR(8) NOT NULL, 
	SOLUONG INT, 
	GIA DECIMAL (19,4)
);

ALTER TABLE CT_DMVC
ADD CONSTRAINT PK_CT_DMVC PRIMARY KEY (MADON, MAVC)

CREATE TABLE THEKHACHHANG 
(
	MATHE CHAR(8) PRIMARY KEY, 
	MAKH CHAR(8), 
	NGAYLAP DATE
);

CREATE TABLE TAIKHOAN 
(
	USRNAME CHAR(8) PRIMARY KEY, 
	PASSWRD VARCHAR(50),
	TK_TYPE INT
);

CREATE TABLE LICHLAMVIEC 
(
	MANV CHAR(8) PRIMARY KEY, 
	NGAYAPDUNG DATE, 
	THOIGIANAPDUNG INT, 
	MON INT, 
	TUE INT,
	WED INT, 
	THU INT, 
	FRI INT, 
	SAT INT,
	SUN INT
);

CREATE TABLE LICHRANH
(
	MANV CHAR(8) PRIMARY KEY, 
	MON INT, 
	TUE INT,
	WED INT, 
	THU INT, 
	FRI INT, 
	SAT INT,
	SUN INT
);

ALTER TABLE LICHLAMVIEC 
ADD CONSTRAINT FK_NV_LLV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)

ALTER TABLE LICHRANH 
ADD CONSTRAINT FK_NV_LR FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)

ALTER TABLE HOADON 
ADD DOTTT INT

ALTER TABLE HOADON 
ADD TINHTRANG BIT

ALTER TABLE HOSOTIEMCHUNG 
ADD CONSTRAINT FK_KH_HSTC FOREIGN KEY(MAKH) REFERENCES KHACHHANG (MAKH)

ALTER TABLE CT_HSTC 
ADD CONSTRAINT FK_VC_CT_HSTC FOREIGN KEY (MAVC) REFERENCES VACCINE (MAVC)

ALTER TABLE CT_HSTC
ADD CONSTRAINT FK_HS_CT_HSTC FOREIGN KEY (MAHS) REFERENCES HOSOTIEMCHUNG (MAHS)

ALTER TABLE CT_DSDAT
ADD CONSTRAINT FK_DS_CT_DSDAT FOREIGN KEY (MADS) REFERENCES DSDATVACCINE (MADS)

ALTER TABLE CT_DSDAT
ADD CONSTRAINT FK_VC_CT_DSDAT FOREIGN KEY (MAVC) REFERENCES VACCINE (MAVC)

ALTER TABLE PHIEUDKTIEM 
ADD CONSTRAINT FK_KH_PDKT FOREIGN KEY(MAKH) REFERENCES KHACHHANG (MAKH)

ALTER TABLE THEKHACHHANG 
ADD CONSTRAINT FK_KH_THE FOREIGN KEY(MAKH) REFERENCES KHACHHANG (MAKH)

ALTER TABLE DONMUAVC
ADD CONSTRAINT FK_KH_DON FOREIGN KEY(MAKH) REFERENCES KHACHHANG (MAKH)

ALTER TABLE HOADON 
ADD CONSTRAINT FK_PDKT_HOADON FOREIGN KEY (MAPDKTIEM) REFERENCES PHIEUDKTIEM (MAPDKTIEM)

ALTER TABLE CT_DMVC
ADD CONSTRAINT FK_DON_CT_DMVC FOREIGN KEY (MADON) REFERENCES DONMUAVC (MADON)

ALTER TABLE CT_DMVC
ADD CONSTRAINT FK_VC_CT_DMVC FOREIGN KEY (MAVC) REFERENCES VACCINE (MAVC)

ALTER TABLE DSDATVACCINE 
ADD CONSTRAINT FK_NV_DSDAT FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)

ALTER TABLE TAIKHOAN 
ADD CONSTRAINT FK_NV_TK FOREIGN KEY (USRNAME) REFERENCES NHANVIEN (MANV)

ALTER TABLE TAIKHOAN 
ADD CONSTRAINT FK_KH_TK FOREIGN KEY (USRNAME) REFERENCES KHACHHANG (MAKH)